DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS TRANSACTION;

CREATE TABLE CUSTOMER(
        CUSTOMER_ID int,
        CUSTOMER_NAME VARCHAR(50)
        );
CREATE TABLE TRANSACTION(
        TRANSACTION_ID int,
        CUSTOMER_ID int,
        TRANSACTION_DATE DATE,
        TRANSACTION_AMOUNT int
        );
